name: Tests

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.3"
    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        coverage: none
        php-version: ${{ matrix.php-version }}
    - run: find -name *.php -exec php -l {} \; 2>&1 1>/dev/null | if grep "^.*error:"; then exit 1; else exit 0; fi
